name: cmid-ui-stg

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_VAULT: /home/runner/work/cmid-ui-ci/cmid-ui-ci/terraform-aws/ci-vault
      CI_ORCH: /home/runner/work/cmid-ui-ci/cmid-ui-ci/terraform-aws/pj-devops
      CI_OOPS: /home/runner/work/cmid-ui-ci/cmid-ui-ci/terraform-aws/devoops

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        env:
          ENV: cm-stg
        run: |
          id;
          df -h;
          pwd;
          docker version;
          docker-compose version;
          packer version;
          terraform version;
          git version;
          printenv | sort ;
          echo "${{ secrets.ALL_{ENV} }}";
          echo "${{ secrets.AWS_ACCESS }}";
          echo "${{ secrets.CICD_ACCESS }}";
          set -x;
          echo "${{ secrets.PEM }}" | > coolermaster-github;
          chmod 600 coolermaster-github;
          eval $(ssh-agent -s);
          echo "${{ secrets.PEM }}" | tr -d '\r' | ssh-add -
          echo "ssh-add coolermaster-github";
          ssh-add -l;
          git clone git@github.com:cm-ctc-sw/cmid-devops-ci.git terraform-aws;
          echo "${{ secrets.AWS_ACCESS }}" > terraform-aws/ci-vault/cloud-aws/coolermaster/${ENV}/aws_access;
          echo "為空我會壞掉" > terraform-aws/ci-vault/ssh/coolermaster-cmid/coolermaster-notprod;
          echo "${{ secrets.ALL_{ENV} }}" > .env;
          cp -r terraform-aws/devoops/reverse-proxy/default.conf default.conf;
          sed -i "s|<HOST>|*.coolermaster.com|g" default.conf;
          sed -i "s|<PROXY_PASS>|http://127.0.0.1:3000|g" default.conf;
          pwd;
          ls;
          sed -in '/ssl/d' Dockerfile;
          docker build -t dockerhub.cloud-interactive.com/coolermaster-ory-${ENV}:latest -t 466701563864.dkr.ecr.us-west-1.amazonaws.com/coolermaster/${ENV}/ory:latest --no-cache .;
          echo "${{ secrets.AWS_ACCESS }}" > ./aws_access;
          eval $(cat ./aws_access);
          aws configure list;
          docker logout;
          aws ecr get-login-password | docker login --username AWS --password-stdin 466701563864.dkr.ecr.us-west-1.amazonaws.com;
          docker push 466701563864.dkr.ecr.us-west-1.amazonaws.com/coolermaster/${ENV}/ory:latest;
          echo "${{ secrets.CICD_ACCESS }}" > ./cicd;
          eval $(cat ./cicd);
          eval $(cat ./aws_access);
          export AWS_ACCOUNT_ID=466701563864;
          export AWS_SESSION_TOKEN=;
          export AWS_REGION=us-west-1;
          eval $(cat terraform-aws/set.sh) && cat terraform-aws/ami-pj-coolermaster.pkr.hcl | envsubst > ./packerfile.pkr.hcl;
          echo "pwding";
          pwd;
          echo "${{ secrets.PEM_NOTPROD }}" > /home/runner/work/cmid-ui-ci/cmid-ui-ci/terraform-aws/ci-vault/ssh/coolermaster-cmid/coolermaster-notprod;
          packer init ./;
          packer validate packerfile.pkr.hcl && packer fmt packerfile.pkr.hcl && packer build -on-error=cleanup packerfile.pkr.hcl;
          cd terraform-aws;
          git config --global user.name cloud-interactive-devops;
          git config --global user.email devops@cloud-interactive.com;
          cat ~/.gitconfig;
          echo "${{ secrets.CREDENTIALS }}" > ~/.aws/credentials
#          terraform init;
#          terraform fmt && terraform validate && terraform apply -var-file=".tfvars" -auto-approve ; git add terraform.tfstate terraform.tfstate.backup ; git commit -m "terraform apply, state change save" ; git push origin master ;
