name: deploy-dev

on:
  push:
    branches: 
      - develop

  do-deployment:
    # needs: run-test-cases
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy newest code to dev machine
      uses: ./.github/actions/run-deploy
      with:
        folder-name: cmid-admin-demo
        branch-name: develop
        env-key: dev
        env-value: ${{ secrets.DEV_ENV }}
        host-name: ${{ secrets.CMID_DEV_HOST }}
        ssh-key: ${{ secrets.SSH_KEY_CMID_DEV_VALUE }}
